menu:
- {name: 'publications', url: '/publications'}
- {name: 'projects', url: '/projects'}
- {name: 'music', url: '/music'}
# - {name: 'cv', url: '/cv'}

social:
# - {icon: 'github', link: 'https://github.com/jkyuha'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/jkyuha'}
- {icon: 'twitter', link: 'https://twitter.com/jkyuha'}

# contacts:
# - {name: 'Kyuha Jung', title: 'Professor', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
